services:
  # -------------------------------------------------------------------------------------------
  jellyfin:
    image: jellyfin/jellyfin:10.9.7
    container_name: jellyfin
    privileged: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/media
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`${HOST_JELLYFIN}`)
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.tls.certresolver=${RESOLVER}
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    restart: unless-stopped
  # ------------------------------------------------------------------------------------------
  jellyseerr:
    image: fallenbagel/jellyseerr:1.9.2
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseer.rule=Host(`${HOST_JELLYSEERR}`)
      - traefik.http.routers.jellyseer.entrypoints=https
      - traefik.http.routers.jellyseer.tls.certresolver=${RESOLVER}
      - traefik.http.services.jellyseer.loadbalancer.server.port=5055
    volumes:
      - ${JELLYSEERR_CONFIG_PATH}:/app/config
    restart: unless-stopped
    networks:
      - proxy
  # ------------------------------------------------------------------------------------------
  gluetun:
    image: qmcgaw/gluetun:v3.38.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESS}
      - TZ=Europe/Rome
      - UPDATER_PERIOD=24h
      - DOT=on
      - DOT_PROVIDERS=cloudflare
      - DOT_IPV6=on
      - DNS_UPDATE_PERIOD=24h
      - BLOCK_MALICIOUS=off
      - UNBLOCK=news.usernetserver.com
    volumes:
      - ${GLUETUN_CONFIG_PATH}:/gluetun
    ports:
      - 8082:8082/tcp # For the web UI of qBittorrent
      - 6881:6881/tcp # For torrent downloads
      - 6881:6881/udp # For torrent downloads
      - 9696:9696/tcp # For the web UI of Prowlarr
      - 7878:7878/tcp # For the web UI of Radarr
      - 8989:8989/tcp # For the web UI of Sonarr
      - 6789:6789/tcp # For the web UI of NZBget
      - 8191:8191/tcp # For the tcp port of flaresolver
      - 8686:8686/tcp # For the web UI of Lidarr
    restart: unless-stopped
    networks:
      - gluetun
  # ------------------------------------------------------------------------------------------
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
    container_name: flaresolverr
    network_mode: service:gluetun
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Rome
    restart: unless-stopped
    depends_on:
      - gluetun
  # -------------------------------------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.20.1
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${PROWLARR_CONFIG_PATH}:/config
    restart: unless-stopped
    depends_on:
      - gluetun
  # -------------------------------------------------------------------------------------------
  radarr:
    image: linuxserver/radarr:5.7.0
    container_name: radarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${MOVIES_PATH}:/movies
    restart: unless-stopped
    depends_on:
      - gluetun
  # -------------------------------------------------------------------------------------------
  sonarr:
    image: linuxserver/sonarr:4.0.8
    container_name: sonarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${SONARR_CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${TV_PATH}:/tv
    restart: unless-stopped
    depends_on:
      - gluetun
  # ---------------------------------------------------------------------------------------------
  lidarr:
    image: lscr.io/linuxserver/lidarr:2.14.5
    container_name: lidarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${LIDARR_CONFIG_PATH}:/config
      - ${MUSIC_PATH}:/music
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun
  # -------------------------------------------------------------------------------------------
  qbittorrent:
    image: linuxserver/qbittorrent:20.04.1
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8082
    volumes:
      - ${QBITTORRENT_CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
  # ------------------------------------------------------------------------------------------
  nzbget:
    image: linuxserver/nzbget:v24.1-ls143
    container_name: nzbget
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${NZBGET_CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
  # ------------------------------------------------------------------------------------------
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:2.22.01
    restart: unless-stopped
    privileged: true
    runtime: nvidia
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
    environment:
      - TZ=Europe/Rome
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
      - nodeIP=0.0.0.0
      - nodePort=8267
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${TDARR_SERVER_PATH}:/app/server
      - ${TDARR_CONFIG_PATH}:/app/configs
      - ${TDARR_LOGS_PATH}:/app/logs
      - ${MEDIA_PATH}:/media
      - ${TDARR_TEMP_PATH}:/temp
    networks:
      - backend
      # ------------------------------------------------------------------------------------------
networks:
  proxy:
    external: true
  gluetun:
    external: true
  backend:
    external: true
